### ISSUE TITLE
Evaluation hangs indefinitely when training on a GPU

### ISSUE THREAD

**Issue by mattiasarro** [tensorflow/tensor2tensor#216]
When training models using an external GPU (macOS), my train phase works well but when ever my model starts evaluation, everything hangs after "INFO:tensorflow:Starting evaluation at `timestamp`". When running with a conda environment that has only non-GPU TensorFlow installed, evluation proceeds as expected.

I've added print statements to the relevant parts in `tensorflow/python/training/evaluation.py` and determined it hangs when `session.run(eval_ops, feed_dict)` is called, i.e. `session.run` never returns. It's evident from the logs that TensorFlow is initializing GPU devices twice - once for the training part:
```
2017-08-09 11:44:31.394040: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:c3:00.0)
2017-08-09 11:44:31.394046: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] Ignoring visible gpu device (device: 1, name: GeForce GT 755M, pci bus id: 0000:01:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 6.1.
2017-08-09 11:44:31.399367: E tensorflow/stream_executor/cuda/cuda_driver.cc:924] failed to allocate 11.00G (11810963456 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
INFO:tensorflow:Restoring parameters from t2t_train/matt/lstm_seq2seq_vae/model.ckpt-1
```
and once when evaluation starts:
```
2017-08-09 12:03:21.160827: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:c3:00.0)
2017-08-09 12:03:21.160850: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] Ignoring visible gpu device (device: 1, name: GeForce GT 755M, pci bus id: 0000:01:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 6.1.
```

I suspect that TF shouldn't create the GPU devices twice, and that the evaluation part (a separate thread?) waiting for the GPU memory to be freed, which never happens. Though the CUDA_ERROR_OUT_OF_MEMORY happens just before train, and the GPU is used during training. Memory usage according to cuda-smi is constantly at 93.67%

There is [a patch in the seq2seq repository](https://github.com/google/seq2seq/blob/master/seq2seq/contrib/experiment.py) for Experiment for  `continuous_train_and_eval` that replaces method calls for `self._call_train(...)` and `self._call_evaluate(...)` with `self._estimator.fit(...)`. I'm not sure shat this should achieve, but the file is described as "A patched handle GPU memory sharing issues." and that's essentially the only change. But it seems that at least in TF has similar changes as in the patch.

Any ideas how to investigate this further?

**Comment by lukaszkaiser** [comment]
Could you check if there is something specific to LSTM (or RNNs) here, or does it happen for other models too? We had some TF bugs with loops-inside-sharded-graphs, I'd like to know if that's a case of this. Could you try some simpler model, like transformer, and see if this still appears? Thanks!

**Comment by mehmedes** [comment]
I observed that while trying to train a transformer model with about 50k vocabularies the training worked but as soon as evaluating started cuda got out of memory. With 40k vocabularies training as well as evaluating worked. 
Shouldn't evaluating not crash if training doesn't.

**Comment by martinpopel** [comment]
I observed out-of-memory error after 17 hours of successful training (with evaluation each 20 minutes or so). My take-home message is to set the batch size low enough (at least 1000 lower than the biggest value that does not fail immediately).

**Comment by mehmedes** [comment]
@martinpopel
> I observed out-of-memory error after 17 hours of successful training

Did it crash during training itself or evaluation?

**Comment by mattiasarro** [comment]
@lukaszkaiser

> Could you check if there is something specific to LSTM (or RNNs) here, or does it happen for other models too?

You're right, this doesn't happen with transformer, only LSTMs.

```
t2t-trainer \
    --problems=wmt_ende_tokens_8k \
    --data_dir=t2t_data \
    --model=lstm_seq2seq_attention \
    --hparams_set=lstm_attention \
    --output_dir=t2t_train/lstm_seq2seq_attention/lstm_attention \
    --t2t_usr_dir t2t_usr \
    --schedule=local_run \
    --local_eval_frequency=5 \
    --train_steps=10
```


What's strange is that sometimes I get the following error early on:

```
...
NFO:tensorflow:Total trainable variables size: 3811200
INFO:tensorflow:Computing gradients for global model_fn.
INFO:tensorflow:Global model_fn finished.
INFO:tensorflow:Create CheckpointSaverHook.
2017-08-10 15:08:39.360975: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:857] OS X does not support NUMA - returning NUMA node zero
2017-08-10 15:08:39.361078: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties:
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:c3:00.0
Total memory: 11.00GiB
Free memory: 10.81GiB
2017-08-10 15:08:39.410970: W tensorflow/stream_executor/cuda/cuda_driver.cc:523] A non-primary context 0x7f96c4549400 exists before initializing the StreamExecutor. We haven't verified StreamExecutor works with that.
2017-08-10 15:08:39.411170: E tensorflow/core/common_runtime/direct_session.cc:138] Internal: failed initializing StreamExecutor for CUDA device ordinal 1: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 1073283072
Traceback (most recent call last):
  File "/Users/m/code/3rd/conda/envs/p2gpu/bin/t2t-trainer", line 82, in <module>
    tf.app.run()
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/Users/m/code/3rd/conda/envs/p2gpu/bin/t2t-trainer", line 78, in main
    schedule=FLAGS.schedule)
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 284, in run
    exp.train_and_evaluate()
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 496, in train_and_evaluate
    self.train(delay_secs=0)
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 276, in train
    hooks=self._train_monitors + extra_hooks)
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 668, in _call_train
    monitors=hooks)
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1003, in _train_model
    config=self._session_config
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 352, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 651, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 481, in __init__
    self._sess = self._coordinated_creator.create_session()
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 541, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 412, in create_session
    init_fn=self._scaffold.init_fn)
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 273, in prepare_session
    config=config)
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 178, in _restore_checkpoint
    sess = session.Session(self._target, graph=self._graph, config=config)
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1292, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 562, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'report_uninitialized_variables_1/boolean_mask/Gather:0' shape=(?,) dtype=string>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
['File "/Users/m/code/3rd/conda/envs/p2gpu/bin/t2t-trainer", line 82, in <module>\n    tf.app.run()', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run\n    _sys.exit(main(_sys.argv[:1] + flags_passthrough))', 'File "/Users/m/code/3rd/conda/envs/p2gpu/bin/t2t-trainer", line 78, in main\n    schedule=FLAGS.schedule)', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 284, in run\n    exp.train_and_evaluate()', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 496, in train_and_evaluate\n    self.train(delay_secs=0)', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 276, in train\n    hooks=self._train_monitors + extra_hooks)', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 668, in _call_train\n    monitors=hooks)', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 289, in new_func\n    return func(*args, **kwargs)', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 455, in fit\n    loss = self._train_model(input_fn=input_fn, hooks=hooks)', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1003, in _train_model\n    config=self._session_config', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 352, in MonitoredTrainingSession\n    stop_grace_period_secs=stop_grace_period_secs)', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 651, in __init__\n    stop_grace_period_secs=stop_grace_period_secs)', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 481, in __init__\n    self._sess = self._coordinated_creator.create_session()', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 541, in create_session\n    self.tf_sess = self._session_creator.create_session()', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 403, in create_session\n    self._scaffold.finalize()', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 192, in finalize\n    default_ready_for_local_init_op)', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 254, in get_or_default\n    op = default_constructor()', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 189, in default_ready_for_local_init_op\n    variables.global_variables())', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/util/tf_should_use.py", line 170, in wrapped\n    return _add_should_use_warning(fn(*args, **kwargs))', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/util/tf_should_use.py", line 139, in _add_should_use_warning\n    wrapped = TFShouldUseWarningWrapper(x)', 'File "/Users/m/code/3rd/conda/envs/p2gpu/lib/python2.7/site-packages/tensorflow/python/util/tf_should_use.py", line 96, in __init__\n    stack = [s.strip() for s in traceback.format_stack()]']
==================================
```

But usually it just freezes here with no GPU/CPU computation taking place.

```
INFO:tensorflow:Total trainable variables size: 3811200
INFO:tensorflow:Computing gradients for global model_fn.
INFO:tensorflow:Global model_fn finished.
INFO:tensorflow:Create CheckpointSaverHook.
2017-08-10 15:22:11.449984: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:857] OS X does not support NUMA - returning NUMA node zero
2017-08-10 15:22:11.450084: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties:
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:c3:00.0
Total memory: 11.00GiB
Free memory: 10.81GiB
2017-08-10 15:22:11.477650: W tensorflow/stream_executor/cuda/cuda_driver.cc:523] A non-primary context 0x7fcc77497400 exists before initializing the StreamExecutor. We haven't verified StreamExecutor works with that.
2017-08-10 15:22:11.477842: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:857] OS X does not support NUMA - returning NUMA node zero
2017-08-10 15:22:11.477967: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 1 with properties:
name: GeForce GT 755M
major: 3 minor: 0 memoryClockRate (GHz) 1.085
pciBusID 0000:01:00.0
Total memory: 1023.56MiB
Free memory: 12.13MiB
2017-08-10 15:22:11.478004: I tensorflow/core/common_runtime/gpu/gpu_device.cc:832] Peer access not supported between device ordinals 0 and 1
2017-08-10 15:22:11.478009: I tensorflow/core/common_runtime/gpu/gpu_device.cc:832] Peer access not supported between device ordinals 1 and 0
2017-08-10 15:22:11.478015: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 1
2017-08-10 15:22:11.478018: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y N
2017-08-10 15:22:11.478021: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   N Y
2017-08-10 15:22:11.478031: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:c3:00.0)
2017-08-10 15:22:11.478045: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] Ignoring visible gpu device (device: 1, name: GeForce GT 755M, pci bus id: 0000:01:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 6.1.
2017-08-10 15:22:11.504300: E tensorflow/stream_executor/cuda/cuda_driver.cc:924] failed to allocate 11.00G (11810963456 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
INFO:tensorflow:Restoring parameters from t2t_train/lstm_seq2seq_attention/lstm_attention/model.ckpt-1
2017-08-10 15:23:19.340782: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 8632 get requests, put_count=5545 evicted_count=1000 eviction_rate=0.180343 and unsatisfied allocation rate=0.485056
2017-08-10 15:23:19.340807: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
INFO:tensorflow:Saving checkpoints for 2 into t2t_train/lstm_seq2seq_attention/lstm_attention/model.ckpt.
INFO:tensorflow:loss = 7.83322, step = 2
2017-08-10 15:26:26.362290: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 2313 get requests, put_count=4327 evicted_count=2000 eviction_rate=0.462214 and unsatisfied allocation rate=0
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:Doing model_fn_body took 0.952 sec.
INFO:tensorflow:This model_fn took 1.678 sec.
INFO:tensorflow:Starting evaluation at 2017-08-10-12:26:34
2017-08-10 15:26:35.267744: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:c3:00.0)
2017-08-10 15:26:35.267774: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] Ignoring visible gpu device (device: 1, name: GeForce GT 755M, pci bus id: 0000:01:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 6.1.
INFO:tensorflow:Restoring parameters from t2t_train/lstm_seq2seq_attention/lstm_attention/model.ckpt-2
```

Not sure if this could be related to my unorthodox GPU installation (self-compiled TF 1.2 on macOS, which is not officially supported), but I'm hoping this problem is part of the library., as you had similar issues with LSTMs

**Comment by mirkobronzi** [comment]
@lukaszkaiser 
same here - transformers works fine (and fast), while seq2seq (lstm based) hangs up at the first evaluation.

Note that it doesn't seem to be related to the model size (i.e., I tried some very small seq2seq models - and they still hang up / while big transformer models can complete the training w/o problems)

**Comment by martinpopel** [comment]
@mehmedes 

>> I observed out-of-memory error after 17 hours of successful training
>
> Did it crash during training itself or evaluation?

Sorry for late reply. It was transformer wmt_encs_tokens_32k, single GPU (with no other jobs) and it crashed during the evaluation:
```
INFO:tensorflow:Evaluation [7/10]  
2017-07-28 02:15:11.363947: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: FIFOQueue '_1104_input_queues/problem_0/batch_examples/bucket_by_sequence_length/bucket/top_queue' is closed and has insufficient elements (requested 1, current size 0)
```

**Comment by lukaszkaiser** [comment]
I think this just means that there were not enough examples to evaluate on, it didn't really crash, right? In any case, in 1.2.0 we use the new data reading API, this should be corrected. Feel free to reopen of course if you see it again!

**Comment by mirkobronzi** [comment]
can anyone confirm that this is not the case anymore (the code hanging) with 1.2.0? (or 1.2.1)?
I have no access at the code now, but I'll try to confirm as soon as I will be able to run an experiment.

**Comment by mirkobronzi** [comment]
@rsepassi : is this fix here
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/input_fn_builder.py#L186
related to this issue?

I incorporate this code, but I see the same hanging behaviour..
(talking about the dev evaluation/annotation during training)

**Comment by walmsley** [comment]
I'm also getting this hanging behaviour running seq2seq with tensorflow r1.3

**Comment by kolloldas** [comment]
I'm facing the same issue when using Neural GPU (T2T1.2/TF1.3 on google cloud). I guess the only way now is to train on GPU and evaluate on CPU (setup another virtualenv where you install the CPU only version of Tensorflow)

**Comment by rsepassi** [comment]
@kolloldas could you confirm that you're using the latest T2T version (1.2.4) and TensorFlow version (1.3)?
What's the command line you launched with?
And is it the case the it does not hang when using the CPU-only version of TensorFlow or have you not actually tried that?

**Comment by kolloldas** [comment]
@rsepassi I can confirm that I'm using T2T 1.2.4 and TF 1.3. The GPU is Tesla K80. 

I did run evaluation on CPU-only version of TensorFlow on Google Cloud; it did not hang..

The command line I used is:
```
t2t-trainer --t2t_usr_dir=/mnt/data/ml/t2t/dp --data_dir=data_lcs_len --problems=dp_lcs_length --model=diagonal_neural_gpu --hparams_set=neuralgpu_1 --hparams=shared_embedding_and_softmax_weights=0 --output_dir=model_dngpu --train_steps=5000 --eval_steps=100 --local_eval_frequency=5001
```
[I'm using my own custom dataset]

**Comment by zh794390558** [comment]
I  have the same problem with blstm, with `--schedule 'train'` , `--schedule 'evalution'`  or '--schedule 'test'', but `--schedule 'train_and_evaluate'`

> INFO:tensorflow:Global model_fn finished.
INFO:tensorflow:Create CheckpointSaverHook.
2017-12-29 07:38:44.128222: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA

2017-12-29 07:38:44.851032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:05:00.0
totalMemory: 11.90GiB freeMemory: 11.74GiB
2017-12-29 07:38:44.851088: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: TITAN Xp, pci bus id: 0000:05:00.0, compute capability: 6.1)

> 2017-12-29 07:43:23.631197: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-12-29 07:43:24.383548: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:05:00.0
totalMemory: 11.90GiB freeMemory: 11.74GiB
2017-12-29 07:43:24.383603: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: TITAN Xp, pci bus id: 0000:05:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from d/model.ckpt-1

**Comment by keerthanpg** [comment]
Was this issue solved? Im facing this with lstms.
