### ISSUE TITLE
Not using Gpu but cpu

### ISSUE THREAD

**Issue by Jong-Won** [tensorflow/tensor2tensor#414]
I am running the training scripts , but only cpu is used instead of gpu.

`export CUDA_VISIBLE_DEVICES=2,3,4

PROBLEM=translate_enzh_wmt8k
MODEL=transformer
HPARAMS=transformer_base_single_gpu

T2T_DIR=/home6/zy/tensor2tensor
DATA_DIR=${T2T_DIR}/t2t_data
TMP_DIR=${T2T_DIR}/tmp/t2t_datagen
TRAIN_DIR=${T2T_DIR}/t2t_train/$PROBLEM/$MODEL-$HPARAMS

t2t-trainer \
	--data_dir=$DATA_DIR \
	--problems=$PROBLEM \
	--model=$MODEL \
	--hparams_set=$HPARAMS \
	--output_dir=$TRAIN_DIR \
	--worker_gpu=4`
![shot](https://user-images.githubusercontent.com/16019517/32707874-dea077aa-c861-11e7-8093-5581474d90e5.png)

the 2 process are not tensor2tensor

thank you

**Comment by martinpopel** [comment]
You ask for four worker GPUs, but you set only three devices visible.

**Comment by Jong-Won** [comment]
I set --worker_gpu=1 and CUDA_VISIBLE_DEVICES=2, but it still do not use gpu

log : INFO:tensorflow:datashard_devices: ['gpu:0']

**Comment by rsepassi** [comment]
Check that you have `tensorflow-gpu` installed (`pip list`).

And please provide the console output of the trainer. 

You should see logs like the following for each GPU:

```
I1113 13:18:03.943892   23752 gpu_device.cc:1154] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:02:00.0, compute capability: 6.1)
```

**Comment by Jong-Won** [comment]
thanks for your reply. I have solve the problem. the problem is that tensorflow in my environment is cpu version. 

Thank you

**Comment by rsepassi** [comment]
Cool, glad we found the cause.
